### ISSUE TITLE
Validating strftime-like strings

### ISSUE THREAD

**Issue by whatyouhide** [hrzndhrn/datix#1]
Heyo! 👋 

I'd love to use this library to parse strftime-formatted strings in order to avoid having to pull in Timex, which does a lot more than I need.

One functionality that I’d need that this library doesn't provide is **validating the format strings**. Something like:

```elixir
Datix.validate("%Y-%m-%d")
#=> :ok
```

After a quick glance at the code, it seems like we could introduce a middle abstraction that represents a "compiled" strftime string. Something like:

```elixir
%Datix.Compiled{format: [{:exact_char, ?d}, {:modifier, ?Y, ...}, ...]}
```

We could then slightly change the API to look like this:

```elixir
# New function:
@spec validate(String.t()) :: {:ok, Datix.Compiled.t()} | {:error, reason :: term()}

# Updated existing function(s):
@spec parse(format :: String.t() | Datix.Compiled.t(), String.t(), keyword()) :: ...
```

I would have bandwidth to work on this if you think it's a good idea. 🙃 I think it does belong in a library like Datix, since you're already implementing the strftime parsing. Looking forward to chatting more! Thanks in advance. 💟

**Comment by NickNeck** [comment]
Hello. That's exactly what `datix` is for. `timex` is great but most of the time too much. Therefore I wrote `datix`, `tox` and `time_zone_info`, to have packages they do one job.

Your proposed enhancements are very welcome.

Maybe we can call the new function:
```elixir
@spec compile(String.t()) :: {:ok, Datix.Compiled.t()} | {:error, reason :: term()}
```
Do you want to switch the arguments in the `parse/3` functions? Currently, they look like this:
```elixir
@spec parse(date_time :: String.t(), format :: String.t(), opts :: keyword()) :: ...
```
I would therefore suggest 
```elixir
@spec parse(date_time :: String.t(), format :: String.t() | Datix.Compiled.t(), opts :: keyword()) :: ...
```
WDYT?

Thank you for your contribution.
