### ISSUE TITLE
Leading zeros in integers

### ISSUE THREAD

**Issue by whatyouhide** [hrzndhrn/datix#11]
Many strptime specs (such as [this one](https://pubs.opengroup.org/onlinepubs/007904875/functions/strptime.html)) specify that in most modifiers that accept integers (such as `%m` for example):

> leading zeros are permitted but not required

This is currently not true in Datix. This is a counter example:

```elixir
iex> Datix.strptime("1", "%m")
{:error, ...}
```

I think we should support this. This is especially useful in informal dates. You could write today's date as `8/5/2022` (with "US format").

**Comment by NickNeck** [comment]
Good point. I think it makes sense to do it like in other implementations.

The question then is how we deal with paddings in general.
```elixir
date = ~D[2022-08-05]

f1 = "%Y/%d/%m"
f2 = "%Y/%-d/%-m"
f3 = "%Y/%_d/%_m"
f4 = "%Y/%0d/%0m"

s1 = Calendar.strftime(date, f1) |>IO.inspect(label: :s1)
Datix.Date.parse(s1, f1) |> IO.inspect(label: :s1f1)
Datix.Date.parse(s1, f2) |> IO.inspect(label: :s1f2)
Datix.Date.parse(s1, f3) |> IO.inspect(label: :s1f3)
Datix.Date.parse(s1, f4) |> IO.inspect(label: :s1f4)

s2 = Calendar.strftime(date, f2) |> IO.inspect(label: :s2)
Datix.Date.parse(s2, f1) |> IO.inspect(label: :s2f1)
Datix.Date.parse(s2, f2) |> IO.inspect(label: :s2f2)
Datix.Date.parse(s2, f3) |> IO.inspect(label: :s2f3)
Datix.Date.parse(s2, f4) |> IO.inspect(label: :s2f4)

s3 = Calendar.strftime(date, f3) |> IO.inspect(label: :s3)
Datix.Date.parse(s3, f1) |> IO.inspect(label: :s3f1)
Datix.Date.parse(s3, f2) |> IO.inspect(label: :s3f2)
Datix.Date.parse(s3, f3) |> IO.inspect(label: :s3f3)
Datix.Date.parse(s3, f4) |> IO.inspect(label: :s3f4)

# the same as s1
# Calendar.strftime(date, f4) |> IO.inspect(label: :s4)
```
```txt
s1: "2022/05/08"
s1f1: {:ok, ~D[2022-08-05]}
s1f2: {:ok, ~D[2022-08-05]}
s1f3: {:ok, ~D[2022-08-05]}
s1f4: {:ok, ~D[2022-08-05]}
s2: "2022/5/8"
s2f1: {:ok, ~D[2022-08-05]}
s2f2: {:ok, ~D[2022-08-05]}
s2f3: {:ok, ~D[2022-08-05]}
s2f4: {:ok, ~D[2022-08-05]}
s3: "2022/ 5/ 8"
s3f1: {:error, %Datix.ParseError{modifier: "%d", reason: :invalid_integer}}
s3f2: {:error,
 %Datix.ParseError{modifier: nil, reason: {:expected_exact, "/", " 5/ 8"}}}
s3f3: {:ok, ~D[2022-08-05]}
s3f4: {:error, %Datix.ParseError{modifier: "%d", reason: :invalid_integer}}
```
Would it then make sense that all these examples return an `:ok` tuple?

**Comment by whatyouhide** [comment]
I don't really know. I think a good behaviour could be:

  1. If you don't specify padding in modifiers, then `0` padding or no padding is allowed
  2. If you specify `-` padding, then no padding is allowed (not even zeros)
  3. If you specify `_` then spaces are allowed
  4. If you specify `0` then zeros are allowed

This way, IMO, kind of matches the idea that if in my format string I specify a padding then I _want_ that padding to be there. If not, then I want to be relaxed about it. Thoughts?

**Comment by NickNeck** [comment]
That sounds good 👍 .

**Comment by whatyouhide** [comment]
I thought more about this, and I’m thinking that being relaxed here might be better. Getting all the rules for parsing according to padding is nasty, and I’m not sure folks would want such precision. So the approach of this PR would be alright with me (basically, accept leading zeros whatever the padding). Thoughts?

**Comment by NickNeck** [comment]
I am fine with that.

**Comment by whatyouhide** [comment]
@NickNeck would it be ok to release 0.3.1? 🙃

**Comment by NickNeck** [comment]
@whatyouhide it is already released. Thank you for all that work on `datix`.
