### ISSUE TITLE
Parsing 2-digit years

### ISSUE THREAD

**Issue by whatyouhide** [hrzndhrn/datix#6]
Right now, it seems like Datix parses 2-digit years by not adding any notion of "century".

```elixir
Datix.Date.parse("18/12/30", "%y/%m/%d")
#=> {:ok, ~D[0018-12-30]}
```

The reason this is problematic is that I can't perform my own "century addition" after parsing, since if the year is `18` I don't know if it came from a `18` parsed with `%y` or a `0018` parsed with `%Y`.

## Existing Stuff

Libraries such as Timex perform a calculation ([code](https://github.com/bitwalker/timex/blob/767de3ff77d6fefb8be9af09b09c3e2a746c4564/lib/parse/datetime/parser.ex#L296-L300)) based off of the current century (which they calculate [here](https://github.com/bitwalker/timex/blob/767de3ff77d6fefb8be9af09b09c3e2a746c4564/lib/timex.ex)). 

I think Timex's approach might be possibly bit too "magic" and doesn't allow for customization of a "pivot year", which is how folks seem to refer to this when talking about this strptime-related issue (see [this StackOverflow question](https://stackoverflow.com/questions/16600548/how-to-parse-string-dates-with-2-digit-year) for example).

The [Linux `strptime` documentation]() says that `%y` represents:

> The year within century (0–99).  When a century is not otherwise specified, values in the range 69–99 refer to years in the twentieth century (1969–1999); values in the range 00–68 refer to years in the twenty-first century (2000–2068).

## Possible Solutions

I don't think hardcoding the century makes this software particularly future-proof. However, I'd like to introduce maybe the concept of a "pivot year" in the options for `Datix.Date.new/2`. That way, we could emulate Linux's behaviour with:

```elixir
Datix.Date.parse!("18/12/30", "%y/%m/%d", pivot_year: 69)
#=> ~D[2018-12-30]

Datix.Date.parse!("98/12/30", "%y/%m/%d", pivot_year: 69)
#=> ~D[1998-12-30]

Datix.Date.parse!("90/12/30", "%y/%m/%d", pivot_year: 91)
#=> ~D[2090-12-30]
```

Do you have any thoughts on this problem? cc @wojtekmach too, would love to hear your thoughts 😉

**Comment by NickNeck** [comment]
I have struggled to came up with good solution for this problem. I didn't want to do any "magic" here. Therefore, the idea was to set everything to 0 that cannot be read as information from the input string.  
But I like the idea with the `pivot_year`

**Comment by wojtekmach** [comment]
I assume :pivot_year is required (i.e. we do _not_ default to 69) when %y is given? I think being explicit here makes a lot of sense.
