### ISSUE TITLE
Zone abbreviation in DateTime structs

### ISSUE THREAD

**Issue by whatyouhide** [hrzndhrn/datix#7]
The `DateTime` Elixir struct has a field called `:zone_abbr`. Should we fill it in when parsing the zone abbreviation, which we do in `Datix.DateTime.parse/3`?

**Comment by NickNeck** [comment]
`Datix.DateTime.parse/3` in an extra tuple.
```elixir
Datix.DateTime.parse("2018/12/30 11:23:55 CEST+0200", "%Y/%m/%d %H:%M:%S %Z%z")
{:ok, ~U[2018-06-30 09:23:55Z], {"CEST", 7200}}
```
Because it is not possible to build a completely correct `DateTime` structure from the infos. The `DateTime` needs `:std_offset` and `:utc_offset`. If we want to set `:zone_abbr` we would need more infos about the time zone.

**Comment by NickNeck** [comment]
Maybe we should rewrite `Datix.DateTime.parse/3`. It is a bit confusing that `parse` and `parse!` have different return values. `parse` returns a 3-tuple and `parse!` just a `DateTime`. I think we can add `:time_zone` to the `opts`. This option gets a function like `(NaiveDatetime.t(), zone_abr :: String.t(), offset :: integer -> Datetime)`. The default would handle `"UTC"` and/or an offset of `0`. Everything else would be a task for the user of `datix`.

**Comment by whatyouhide** [comment]
@NickNeck I like that. This would be a required option when which modifiers are present?

**Comment by NickNeck** [comment]
If would suggest we provide a default to handle "UTC".
Something like this.
```elixir
@spec default_time_zone(NaiveDateTime.t(), String.t(), integer) :: {:ok, Datetime.t()} | {:error, Datix.ValidationError.t()}
def default_time_zone(naive_datetime, zone_abbr, offset) do
  case {zone_abbr, offset} do
    {nil, nil} -> {:ok, DateTime.from_naive(naive_datetime, "Etc/UTC")}
    {"UTC", 0} -> {:ok, DateTime.from_naive(naive_datetime, "Etc/UTC")}
     ....
    _unknown -> {:error, %ValidationError{reason: :unknown_time_zone, module: Datix.DateTime}}
  end
end
```

**Comment by whatyouhide** [comment]
@NickNeck working on this.
